import Head from 'next/head';
import React from 'react';

import styles from '../../styles/Home.module.css';

function Solutions(props) {
  return (
    <>
      <Head>
        <title>AvenueCorp - Solutions</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='pixels/favicon.ico' />
      </Head>
      <div className={`body-sub-container ${styles.main}`}>
        Solutions
      </div>
    </>
  );
}

export default Solutions;
