import React from "react";
import Sections from "../Components/Sections";
import Head from 'next/head';

import styles from "../styles/Home.module.css";
import pageStyles from "../styles/Page.module.css";

function about(props) {
  const bannerDetails = {
    title: "Welcome to Avenue Corporation",
    description: `Avenue Packs, Fully dedicated to integrity, quality and innovation. <br/> We strive to offer a unique combination of integrated packaging solutions and services unmatched by any other company to be the best.`,
    image: "about.jpg",
    alt: "technology banner",
  };
  return (
    <>
      <Head>
        <title>Avenue Corporation - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="pixels/favicon.ico" />
      </Head>

      <div className={`body-sub-container ${pageStyles.container}`}>
        <Sections.PageBanner {...bannerDetails} />
        <div className={`${pageStyles.row} ${pageStyles.row_padding_rem_4} ${pageStyles.row_text_center} ${pageStyles.row_blue_bg}`}>
          <div className={`${pageStyles.row_cell_one_out_of_four} ${pageStyles.row_cell_one_out_of_four__height_15_rem} ${pageStyles.row_white_bg} ${pageStyles.row_padding_rem_1}`}>
            <h2>About Us</h2>
            <p>Avenue Corporation aspires to be a collaborative corporate organization rather than a competitive one, delivering Industrial Packaging Solution across the world. Our fervent aim is to build a product that continuously provides value for all stakeholders while reducing carbon footprint and ecological sustainability.</p>
          </div>
          <div className={`${pageStyles.row_cell_one_out_of_four} ${pageStyles.row_cell_one_out_of_four__height_15_rem} ${pageStyles.row_white_bg} ${pageStyles.row_padding_rem_1}`}>
            <h2>Who We Are</h2>
            <p>Avenue Corporation is a well-organized, well-engineered industrial packaging manufacturer and developer of customized packaging solutions for the global market. Our dedication to you is underpinned by our experience in offering strategic solutions in the automotive supply chain using cutting-edge packaging technologies in the automotive supply chain.</p>
          </div>
        </div>
        {/* <Sections.GallarySlider /> */}
      </div>
    </>
  );
}

export default about;
