import React, { useContext } from "react";
import Sections from "../Components/Sections";
import Head from "next/head";

import pageStyles from "../styles/Page.module.css";
import NavigationContext from "../Contexts/NavigationContext";

function about(props) {
  const { siteConfig } = useContext(NavigationContext);
  const bannerDetails = {
    title: `Welcome to ${siteConfig.name}`,
    description: `${siteConfig.name}, Fully dedicated to integrity, quality and innovation. <br/> We strive to offer a unique combination of integrated packaging solutions and services unmatched by any other company to be the best.`,
    image: "about-banner.jpeg",
    alt: "technology banner",
  };
  return (
    <>
      <Head>
        <title>{siteConfig.name} - About Us</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="pixels/favicon.ico" />
      </Head>

      <div className={`body-sub-container ${pageStyles.container}`}>
        <Sections.PageBanner {...bannerDetails} />
        <div
          className={`${pageStyles.row} ${pageStyles.row_padding_rem_4} ${pageStyles.row_text_center} ${pageStyles.row_blue_bg} bg-dark-blue`}
        >
          <div
            className={`about-us--home-page ${pageStyles.row_cell_one_out_of_two} ${pageStyles.row_cell_one_out_of_two__height_15_rem} ${pageStyles.row_padding_rem_1}`}
          >
            <div className="about-us--home-page-outer">
              <h3 className="about-us--home-page-inner">About Us</h3>
            </div>
            <p>
              {siteConfig.name} aspires to be a collaborative corporate
              organization rather than a competitive one, delivering Industrial
              Packaging Solution across the world. Our fervent aim is to build a
              product that continuously provides value for all stakeholders
              while reducing carbon footprint and ecological sustainability.
            </p>
          </div>
          <div
            className={`about-us--home-page  ${pageStyles.row_cell_one_out_of_two} ${pageStyles.row_cell_one_out_of_two__height_15_rem} ${pageStyles.row_padding_rem_1}`}
          >
            <div className="about-us--home-page-outer">
              <h3 className="about-us--home-page-inner">Who we are</h3>
            </div>
            <p>
              {siteConfig.name} is a well-organized, well-engineered industrial
              packaging manufacturer and developer of customized packaging
              solutions for the global market. Our dedication to you is
              underpinned by our experience in offering strategic solutions in
              the automotive supply chain using cutting-edge packaging
              technologies in the automotive supply chain.
            </p>
          </div>
        </div>
        {/* <Sections.GallarySlider /> */}
      </div>
    </>
  );
}

export default about;
