import Head from 'next/head';
import Link from 'next/link';
import React from 'react';
import SwiperSlider from '../Components/SwiperSlider';
import styles from '../styles/Home.module.css';

function Home({ props }) {
  return (
    <div className={`body-container ${styles.container}`}>
      <Head>
        <title>Avenue Corporation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='pixels/favicon.ico' />
      </Head>
      <main className={`body-sub-container ${styles.main}`}>
        <SwiperSlider />
        <div className={styles.aboutUs}>
          <label className={styles.aboutUsTitle}>About Us</label>
          <div className={styles.aboutUsBody}>
            <div className={styles.aboutUsBody_description}>
              <p>
                The idea of Econovus is to provide Innovative and sustainable
                packaging solution to reduce carbon footprint by up to 93% and
                cost reduction by 10-15%. The solution consist of using a unique
                Engineering approach and the usage of high technology
                eco-friendly material.
              </p>
            </div>
            <div className={styles.aboutUsBody_actions}>
              <div className={styles.aboutUsButton}><Link href="/about"><a>About Us</a></Link></div>
              <div className={styles.aboutUsButton}><Link href="/solutions"><a>Solutions</a></Link></div>
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
export default Home;
