import Head from 'next/head';
import React from 'react';
import styles from '../styles/Home.module.css';

import Sections from '../Components/Sections';

function Home({ props }) {
  return (
    <div className={`body-container ${styles.container}`}>
      <Head>
        <title>Avenue Corporation</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='../pixels/favicon.ico' />
      </Head>
      <main className={`body-sub-container ${styles.main}`}>
        <Sections.HomeSlider />
        <Sections.AboutUs />
        <Sections.Solutions />
        <Sections.WhyUs />
        <Sections.MeetOurClients showClientSlider={true}/>
        <Sections.WorkCompleted reqCount={2500} />
        <Sections.ContactForm />
      </main>
    </div>
  );
}
export default Home;

