import Head from 'next/head';
import React from 'react';
import Sections from '../Components/Sections';

import styles from '../styles/Home.module.css';
import pageStyles from '../styles/Page.module.css';

function Sustainability(props) {
  const bannerDetails = {
    title: 'Sustainability',
    description: `We believe in making our planet a better place to live. Avenue Corporation Packaging Solution can help you achieve your environmental goals.`,
    image: 'technology.webp',
    alt: 'about banner',
  };
  return (
    <>
      <Head>
        <title>AvenueCorp - Sustainability</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='pixels/favicon.ico' />
      </Head>
      <div className={`body-sub-container ${pageStyles.container}`}>
        <Sections.PageBanner {...bannerDetails} />
      </div>
    </>
  );
}

export default Sustainability;
