import Head from 'next/head';
import React from 'react';

import styles from '../styles/Home.module.css';

function Sustainability(props) {
  return (
    <>
      <Head>
        <title>AvenueCorp - Sustainability</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='pixels/favicon.ico' />
      </Head>
      <div className={`body-sub-container ${styles.main}`}>
      Sustainability
      </div>
    </>
  );
}

export default Sustainability;
