import Head from "next/head";
import React from "react";
import Sections from "../Components/Sections";

import pageStyles from "../styles/Page.module.css";

function Sustainability(props) {
  const bannerDetails = {
    title: "Sustainability",
    description: `We believe in making our planet a better place to live. Avenue Corporation Packaging Solution can help you achieve your environmental goals.`,
    image: "technology.webp",
    alt: "about banner",
  };
  return (
    <>
      <Head>
        <title>Avenue Corporation - Sustainability</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="pixels/favicon.ico" />
      </Head>
      <div className={`body-sub-container ${pageStyles.container}`}>
        <Sections.PageBanner {...bannerDetails} />
        <div className={`${pageStyles.row} ${pageStyles.vision}`}>
          <div className={pageStyles.sustainabilityVision__Title}>
            Sustainability Vision and CSR
          </div>
          <div className={pageStyles.sustainabilityVision__Description}>
            Eco-friendly, sustainable packaging solution is our stronghold.
            Throughout our product and services range, we ensure that we meet
            our client’s needs in the most cost-effective and safest possible
            way. The raw materials we use and the engineering process we follow
            are envisioned to deliver peace of mind now and to the generation
            next.
          </div>
        </div>
        <div className={`${pageStyles.grid__2} ${pageStyles.vision}`}>

        </div>
      </div>
    </>
  );
}

export default Sustainability;
