import Head from 'next/head';
import React from 'react';
import Sections from '../Components/Sections';

import pageStyles from '../styles/Page.module.css';

function Technology(props) {
  const bannerDetails = {
    title: 'Technology & Innovation',
    description:`Avenue Corporation is happy to provide its clients the creation of unique
    packaging solution with it’s technology and innovation practices.`,
    image: 'technology.webp',
    alt: 'technology banner',
  };
  return (
    <>
      <Head>
        <title>AvenueCorp - Technology</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='pixels/favicon.ico' />
      </Head>
      <div className={`body-sub-container ${pageStyles.container}`}>
        <Sections.PageBanner {...bannerDetails} />
      </div>
    </>
  );
}

export default Technology;
