import Head from "next/head";
import React from "react";
import pageStyles from "../styles/Page.module.css";
import Image from "next/image";

function UnderConstruction({ customClass }) {
  return (
    <>
      <Head>
        <title>Under Construction</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="pixels/favicon.ico" />
      </Head>
      <div className={customClass}>
        <div>
          <Image
            src="/pixels/under_construction.png"
            alt="This part of site is under construction!"
            layout="fill"
          />
        </div>
        <div>
          <h1>
            This site is under construction <span>!</span>
          </h1>
          <h4>
          <u>Vercel Error</u> (E02x3049cc) : Trial deployment subscription has been expired,
            please renew subscription or update cron jobs and deployment
            configuration if already subscribed.
          </h4>
        </div>
      </div>
    </>
  );
}

export default UnderConstruction;
